# Compose file generated automatically

version: '3.6'

services:
  simplerisk:
    environment:
    - FIRST_TIME_SETUP=1
    - FIRST_TIME_SETUP_PASS=FewY7hr3LHp4CRL9v2jg6
    - SIMPLERISK_DB_HOSTNAME=mariadb
    image: simplerisk/simplerisk-minimal:20230331-001
    ports:
    - "80:80"
    - "443:443"

  mysql:
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
    - MYSQL_ROOT_PASSWORD=aef5-IX1D0zIV7w4NEp3U
    image: mysql:8.0

  smtp:
    image: namshi/smtp
