# Compose file generated automatically

version: '3.6'

services:
  simplerisk:
    environment:
    - FIRST_TIME_SETUP=1
    - FIRST_TIME_SETUP_PASS=cPL8F7qw2YNtA-xSgnq4O
    - SIMPLERISK_DB_HOSTNAME=mariadb
    image: simplerisk/simplerisk-minimal:20210305-001
    ports:
    - "80:80"
    - "443:443"

  mariadb:
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
    - MYSQL_ROOT_PASSWORD=cPL8F7qw2YNtA-xSgnq4O
    image: mariadb:10.5

  smtp:
    image: namshi/smtp
