#!/usr/bin/env bash

set -euo pipefail

SCRIPT_LOCATION="$(dirname "$(readlink -f "$0")")"
readonly SCRIPT_LOCATION

if [ $# -eq 1 ]; then
  release=$1
else
  echo "No release version provided. Aborting." && exit 1
fi

cat << EOF > "${SCRIPT_LOCATION}/Dockerfile"
# Dockerfile generated by script
ARG php_version=8.4

EOF

if [ "$release" != "testing" ]; then
	cat << EOF >> "${SCRIPT_LOCATION}/Dockerfile"
FROM alpine/curl:8.12.1 AS downloader

SHELL [ "/bin/ash", "-eo", "pipefail", "-c" ]

RUN mkdir -p /var/www && \\
    curl -sL https://simplerisk-downloads.s3.amazonaws.com/public/bundles/simplerisk-$release.tgz | tar xz -C /var/www

EOF
fi

cat << EOF >> "${SCRIPT_LOCATION}/Dockerfile"
FROM php:\${php_version}-apache

LABEL maintainer="SimpleRisk <support@simplerisk.com>"

ENV version=$release

WORKDIR /var/www

SHELL [ "/bin/bash", "-o", "pipefail", "-c" ]

#  Install required packages, including MySQL client from Debian repos
RUN apt-get update && \\
    apt-get install -y --no-install-recommends \\
        libldap2-dev \\
        libicu-dev \\
        libcap2-bin \\
        libcurl4-gnutls-dev \\
        libpng-dev \\
        libzip-dev \\
        supervisor \\
        cron \\
        ca-certificates \\
        rsyslog \\
        logrotate \\
        curl \\
        # This will install mariadb-client
        default-mysql-client && \\
    apt-get -y autoremove && \\
    apt-get -y purge && \\
    rm -rf /var/lib/apt/lists/*

# Configure all PHP extensions
RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu && \\
    docker-php-ext-install ldap \\
                           mysqli \\
                           pdo_mysql \\
                           curl \\
                           zip \\
                           gd \\
                           intl

# Setting up setcap for port mapping without root and removing packages
RUN setcap CAP_NET_BIND_SERVICE=+eip /usr/sbin/apache2 && \\
    chmod gu+s /usr/sbin/cron && \\
    apt-get -y remove libcap2-bin && \\
    apt-get -y autoremove && \\
    apt-get -y purge

RUN echo "0 0 * * * root /usr/sbin/logrotate /etc/logrotate.d/simplerisk.conf > /dev/null 2>&1" >> /etc/cron.d/logrotate-cron && \\
    chmod 0644 /etc/cron.d/logrotate-cron

# Copying all files
COPY common/ /
EOF
# shellcheck disable=SC2015
if [ "$release" == "testing" ]; then
	cat << EOF >> "${SCRIPT_LOCATION}/Dockerfile"
COPY simplerisk/ /var/www/simplerisk
COPY common/simplerisk.sql /var/www/simplerisk/simplerisk.sql
EOF
else
	echo "COPY --from=downloader /var/www/simplerisk /var/www/simplerisk" >> "${SCRIPT_LOCATION}/Dockerfile"
fi
cat << EOF >> "${SCRIPT_LOCATION}/Dockerfile"

# Configure Apache
RUN echo 'upload_max_filesize = 5M' >> /usr/local/etc/php/conf.d/docker-php-uploadfilesize.ini && \\
	echo 'memory_limit = 256M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini && \\
	echo 'max_input_vars = 3000' >> /usr/local/etc/php/conf.d/docker-php-maxinputvars.ini && \\
	echo 'log_errors = On' >> /usr/local/etc/php/conf.d/docker-php-error_logging.ini && \\
	echo 'error_log = /dev/stderr' >> /usr/local/etc/php/conf.d/docker-php-error_logging.ini && \\
	echo 'display_errors = Off' >> /usr/local/etc/php/conf.d/docker-php-error_logging.ini && \\
# Create SSL Certificates for Apache SSL
	mkdir -p /etc/apache2/ssl/ca /etc/apache2/ssl/simplerisk && \\
# Generate CA
	openssl genrsa -out /etc/apache2/ssl/ca/ca.key 4096 && \\
	openssl req -x509 -new -nodes -key /etc/apache2/ssl/ca/ca.key -sha256 -days 3650 -out /etc/apache2/ssl/ca/ca.crt -subj "/CN=SimpleRisk CA" && \\
# Generate certs
	openssl genrsa -out /etc/apache2/ssl/simplerisk/simplerisk.key 2048 && \\
	openssl req -new -key /etc/apache2/ssl/simplerisk/simplerisk.key -out /etc/apache2/ssl/simplerisk/simplerisk.csr -subj "/CN=localhost" -addext "subjectAltName=DNS:localhost,DNS:simplerisk,IP:127.0.0.1,IP:0.0.0.0" && \\
	openssl x509 -req -days 365 -in /etc/apache2/ssl/simplerisk/simplerisk.csr -CA /etc/apache2/ssl/ca/ca.crt -CAkey /etc/apache2/ssl/ca/ca.key -CAcreateserial -out /etc/apache2/ssl/simplerisk/simplerisk.crt -copy_extensions copyall && \\
	cp /etc/apache2/ssl/ca/ca.crt /usr/local/share/ca-certificates/simplerisk.crt && \\
	chmod 644 /usr/local/share/ca-certificates/simplerisk.crt && \\
	update-ca-certificates && \\
# Activate Apache modules
	a2enmod headers rewrite ssl && \\
	a2enconf security && \\
	sed -i 's/\\(SSLProtocol\\) all -SSLv3/\1 TLSv1.2/g' /etc/apache2/mods-enabled/ssl.conf && \\
	sed -i 's/#\\(SSLHonorCipherOrder on\\)/\\1/g' /etc/apache2/mods-enabled/ssl.conf && \\
	sed -i 's/\\(ServerTokens\\) OS/\\1 Prod/g' /etc/apache2/conf-enabled/security.conf && \\
	sed -i 's/#\\(ServerSignature\\) On/\\1 Off/g' /etc/apache2/conf-enabled/security.conf

# Cleanup /var/www/, creating Simplerisk user on www-data group and setting up ownerships
RUN rm -rf /var/www/html && \\
	useradd -G www-data simplerisk && \\
	mkdir -p /var/log/simplerisk && \\
	mkdir -p /var/log/supervisor && \\
	mkdir -p /var/run/supervisor && \\
	chmod -R 700 /etc/apache2 /var/log/simplerisk /var/run/ /var/www/simplerisk  && \\
	chmod 755 /entrypoint.sh /etc/apache2/foreground.sh && \\
	chown -R simplerisk:www-data /etc/apache2 /var/log/apache2 /var/log/simplerisk /var/log/supervisor /var/run/ /var/www/simplerisk

# Data to save
VOLUME [ "/var/log", "/etc/apache2/ssl", "/var/www/simplerisk" ]

# Using simplerisk user from here
USER simplerisk

# Setting up entrypoint
ENTRYPOINT [ "/entrypoint.sh" ]

# Ports to expose
EXPOSE 80
EXPOSE 443

HEALTHCHECK --interval=1m \\
	CMD curl --fail http://localhost || exit 1

# Start Apache 
CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
EOF
