name: Create new release tag
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config user.name "SimpleRisk Updater"
          git config user.email "support@simplerisk.com"
          git config push.followTags true
          git fetch --tags
      - name: Check if tag does not exist, and generate/push one
        run: |
          TAG_NAME=$(grep "ENV version" simplerisk-minimal/Dockerfile | cut -d '=' -f 2)
          if ! git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            git tag -a $TAG_NAME -m "SimpleRisk $TAG_NAME Release"
          fi
          git push --tags
